#define STRING_NEWLINE "\r\n"
#define STRING_TX "TX:"
#define STRING_RX "RX:"
#define STRING_QUERY_CODE "Enter query code:"
#define STRING_QUERY_SUBCODE "Enter query subcode:"
#define STRING_QUERY_LENGTH "Enter query length:"
#define STRING_QUERY_DATA "Enter query data (max 63, ASCII):"
#define STRING_SENDING_QUERY "Sending query..."
#define STRING_RECEIVE_WAIT "Waiting for start..."
#define STRING_RECEIVE_HEADER "Getting header..."
#define STRING_RECEIVE_DATA "Getting data..."
#define STRING_INVALID "Invalid entry"
