#define STRING_NEWLINE "\n"
#define STRING_TX "TX:\n"
#define STRING_RX "RX:\n"
#define STRING_QUERY_CODE "Enter query code:\n"
#define STRING_QUERY_SUBCODE "Enter query subcode:\n"
#define STRING_QUERY_LENGTH "Enter query length:\n"
#define STRING_QUERY_DATA "Enter query data (max 63, ASCII):\n"
#define STRING_SENDING_QUERY "Sending query...\n"
#define STRING_RECEIVE_WAIT "Waiting for start...\n"
#define STRING_RECEIVE_HEADER "Getting header...\n"
#define STRING_RECEIVE_DATA "Getting data...\n"
